version: "3"
services:
  webapi.local:
    build: .
    ports:
      - "8805:8805"
    command: ./eth-analyse server -run dev
    networks:
      - eth-analyse
    depends_on:
      - psql.local
  psql.local:
    image: glassnode/code-challenge-2020-database:latest
    environment:
      POSTGRES_DB: eth
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "6545:5432"

networks:
  eth-analyse:
